import { Theater } from "./types";

export const bookingData: Theater = {
  maxSeats: 26,
  seatDimension: 28,
  seatGap: 2,
  seatGroups: [
    {
      label: "₹480 RECLINER ROWS",
      seatRows: [
        {
          label: "S",
          seats: [
            {
              id: "S20",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              isSeat: false,
            },
            {
              isSeat: false,
            },
            {
              isSeat: false,
            },
            {
              id: "S18",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S17",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S16",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S15",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S14",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S13",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S12",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S11",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S10",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S09",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S08",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S07",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S06",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S05",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S04",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S03",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S02",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S01",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
          ],
        },
        {
          label: "S",
          seats: [
            {
              id: "S20",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S19",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S18",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S17",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S16",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S15",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S14",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S13",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S12",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S11",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S10",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S09",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S08",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S07",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S06",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S05",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S04",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S03",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S02",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S01",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
          ],
        },

        {
          label: "S",
          seats: [
            {
              id: "S20",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S19",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S18",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S17",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S16",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S15",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S14",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S13",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S12",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S11",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S10",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S09",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S08",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S07",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S06",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S05",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S04",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S03",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S02",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S01",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
          ],
        },

        {
          label: "S",
          seats: [
            {
              id: "S20",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S19",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S18",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S17",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S16",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S15",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S14",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S13",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S12",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S11",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S10",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S09",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S08",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S07",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S06",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S05",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S04",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S03",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S02",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
            {
              id: "S01",
              isSeat: true,
              status: "AVAILABLE",
              price: 480,
              type: "RECLINER",
              isSelected: false,
            },
          ],
        },
      ],
    },
    {
      label: "₹270 PRIME ROWS",
      seatRows: [
        {
          label: "Q",
          seats: [
            {
              id: "Q26",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q25",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q24",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q23",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q22",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q21",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q20",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q19",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q18",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q17",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q16",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q15",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q14",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q13",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q12",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q11",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q10",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q09",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q08",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q07",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q06",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q05",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q04",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q03",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q02",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "Q01",
              isSeat: true,
              status: "AVAILABLE",
              price: 270,
              type: "NORMAL",
              isSelected: false,
            },
          ],
        },
      ],
    },
    {
      label: "₹320 EXTRA LEGROOM ROWS",
      seatRows: [
        {
          label: "L",
          seats: [
            {
              id: "L26",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L25",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L24",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L23",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L22",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L21",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L20",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L19",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L18",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L17",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L16",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L15",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L14",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L13",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L12",
              isSeat: true,
              status: "UNAVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L11",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L10",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L09",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L08",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L07",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L06",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L05",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L04",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L03",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L02",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
            {
              id: "L01",
              isSeat: true,
              status: "AVAILABLE",
              price: 320,
              type: "NORMAL",
              isSelected: false,
            },
          ],
        },
      ],
    },
  ],
};
